name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Fibonacci & FizzBuzz Tests
      id: fibonacci-fizzbuzz-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Fibonacci & FizzBuzz Tests
        setup-command: ''
        command: mvn test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIBONACCI-FIZZBUZZ-TESTS_RESULTS: "${{steps.fibonacci-fizzbuzz-tests.outputs.result}}"
      with:
        runners: fibonacci-fizzbuzz-tests
